version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: journey_mate_db
      POSTGRES_USER: journey_mate_db_user
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
