version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: journey_mate_db
      POSTGRES_USER: journey_mate_db_user
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '86:80'
    depends_on:
      - db

volumes:
  postgres_data:
